version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    user: postgres
    command: postgres -c 'max_connections=50'

volumes:
  postgres_data: 